### ISSUE TITLE
[Bug] 1.18.2 forge: incompatibility with AE2

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [shedaniel/REIPluginCompatibilities-Issues#19]
### What happened?

Spoofed version of JEI is lower than required for AE2
![image](https://user-images.githubusercontent.com/66212375/198932321-3d0e5a6f-bed4-4611-8e83-ed02dc4185d4.png)

### Relevant log output

```shell
No log output is relevant here
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
JEI 10 isn't very supported by other mods, and it is massive effort to support both JEI 9 and JEI 10. Supporting JEI 10 means no support for the mass majority of JEI 9 mods. I am not sure how to go about this.

**Comment by shedaniel** [comment]
This should be resolved now as AE2 now supports JEI 9
