### ISSUE TITLE
[Bug] Almost Unified requires jei 10, but REI Plugin Compatibility is jei 9

### ISSUE THREAD

**Issue by Dr-WeiAL** [shedaniel/REIPluginCompatibilities-Issues#21]
### What happened?

![image](https://user-images.githubusercontent.com/47446553/200186877-3fee4bab-7498-436e-9446-4ea068ad367d.png)

And the other side can't downgrade to jei 9
![image](https://user-images.githubusercontent.com/47446553/200186913-f85249fe-06bd-42e8-9cb2-bbfb4f9b0f8a.png)

Will this problem be solved? Or can it only be downgraded

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9946477/latest.log)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by DAmNRelentless** [comment]
Yeah, Max told me about this. My initial thought was that, since the REI compat layer mimics JEI, an update to JEI 10 would drop JEI 9 support completely, now since it's not alpha anymore.

I'd understand if that's not gonna happen, it's just a really messed up situation right now. It's pretty much the same thing that will happen in the future with Vanilla. Major breaking changes in a minor version.

**Comment by shedaniel** [comment]
Yeah I don't believe dropping support for the majority of JEI plugins is a good idea just to make one or two JEI 10 plugins work. That would mean the new compat layer is non functional until most mods update to JEI 10.

The most unfortunate thing is that this is happening to 1.18.2, which some mods have already moved on to 1.19 and an update to their JEI compat would be unlikely.

**Comment by Dr-WeiAL** [comment]
Strangely enough, all the original JEI9 plugins worked fine when I was using JEI10

**Comment by DAmNRelentless** [comment]
Mods that implemented their JEI plugin on JEI 9.7 work with JEI 10 as well.

**Comment by Dr-WeiAL** [comment]
> Mods that implemented their JEI plugin on JEI 9.7 work with JEI 10 as well.

So theoretically upgrading to jei10 should not affect much, right? I don't know much about these

**Comment by shedaniel** [comment]
No, entire APIs were taken away, even though they were already deprecated in JEI 9.7, they are still supported.

**Comment by shedaniel** [comment]
Relentless got back to me and said Almost Unified should now support JEI 9.
![image](https://user-images.githubusercontent.com/34910653/200649310-057f322f-5749-4595-a7c8-e9d696c85b0a.png)
