### ISSUE TITLE
[Bug] Not able to hotkey after using RS's search bar.

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [shedaniel/REIPluginCompatibilities-Issues#27]
### What happened?

Title.
Repro:
1. Open up an RS grid
2. Try to use R to look at the recipe of an item, or any other keybind for that matter
3. Focus the search bar, unfocus the searchbar (you don't even need to search for anything)
4. Try to use R / others again; this time it doesn't work - you're stuck with either having to reopen the gui or use rei's search bar; which is inconvenient.

### Relevant log output

```shell
Irrelavant
```

### Anything else?

I'm filing this on GH after this: https://i.imgur.com/JS7hY3F.png so that maybe it can be fixed :)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Should be fixed with https://github.com/shedaniel/RoughlyEnoughItems/commit/2caa595aa94d46ddaefc5ecdb79f7ec834f7eae8
