### ISSUE TITLE
[Bug] Issue button on curseforge links to rei issues

### ISSUE THREAD

**Issue by NordicGamerFE** [shedaniel/REIPluginCompatibilities-Issues#29]
### What happened?

I dont know if this is intended but the issue button on curseforge links to https://github.com/shedaniel/RoughlyEnoughItems/issues

### Relevant log output

```shell
n/a
```

### Anything else?

n/a

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Thank you! I have changed the issues link
