### ISSUE TITLE
[Bug] Numismatic overhaul shop inventory doesn't hide the REI screen as intended. Forge 1.18.2

### ISSUE THREAD

**Issue by Warhand** [shedaniel/REIPluginCompatibilities-Issues#37]
### What happened?

Numismatic overhaul has a shop block that allows players to sell and buy items between themselves. And by default it will disable the JEI menu while the shop inventory is open, because otherwise it will cover up important parts of the shops UI. However REI does not carry over this functionality, leading to the shop being unusable.

REI should mimic JEI's functionality and hide itself when the Numismatic overhaul shop UI is open, I have tested it and can confirm it does this with JEI, so its most likely an issue with REI's compat layer.

### Relevant log output

```shell
Latest.log: https://gist.github.com/Warhand/b8c45b1e945b24289a76f056596098bb
REI.log: https://gist.github.com/Warhand/fdb2a7f9b460e92dc45c611e72398a0e
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
FIxed in latest builds
