### ISSUE TITLE
[Bug] Iron's Spells n Spellbooks cannot show recipes when using REIPC

### ISSUE THREAD

**Issue by Pixl64** [shedaniel/REIPluginCompatibilities-Issues#51]
### What happened?

Issue originally created in the Iron's Spells Github: https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/129

The error message below is shown when using REIPC and Iron's Spells and will not go away. 
![image](https://github.com/shedaniel/REIPluginCompatibilities-Issues/assets/85389249/bd57317c-40ee-49af-86a2-02034daa4b37)

Trying without Iron's Spells works fine, and without REIPC it works correctly as well, but other modded recipes are not shown so removing REIPC is not an option for me. 

### Relevant log output

```shell
https://gist.github.com/Pixl64/eb65ecd1368ca8e2adaa6f0dee48e264   rei-issues.log
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Should be fixed in build 69+
